services:
## PHP
  php:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: ./docker/dev/php/Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION:-8.2}
        ENV: ${ENV:-development}
    volumes:
      - ./app:/var/www/html
    depends_on:
      - postgres
    networks:
      - dev_net
## NGINX
  nginx:
    image: nginx:alpine
    volumes:
      - ./app:/var/www/html
      - ./docker/dev/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - php
    networks:
      - dev_net
## postgres
  postgres:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-defaultpassword}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    ports:
      - "5432:5432"
    networks:
      - dev_net
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data:rw
networks:
  dev_net:
    name: dev_net
    driver: bridge
    external: true   # Network already exists in another project! then use this
